name: 'Debugging with tmate'
description: 'Debug your GitHub Actions Environment interactively by using SSH or a Web shell'
branding:
  icon: terminal
author: 'Max Schmitt'
runs:
  using: 'node16'
  main: 'lib/index.js'
inputs:
  sudo:
    description: 'If apt should be executed with sudo or without'
    required: false
    default: 'auto'
  install-dependencies:
    description: 'Whether or not to install dependencies for tmate on linux (openssh-client, xz-utils)'
    required: false
    default: 'true'
  limit-access-to-actor:
    description: 'If only the public SSH keys of the user triggering the workflow should be authorized'
    required: false
    default: 'false'
  tmate-server-host:
    description: 'The hostname for your tmate server (e.g. ssh.example.org)'
    required: false
    default: ''
  tmate-server-port:
    description: 'The port for your tmate server (e.g. 2222)'
    required: false
    default: ''
  tmate-server-rsa-fingerprint:
    description: 'The RSA fingerprint for your tmate server'
    required: false
    default: ''
  tmate-server-ed25519-fingerprint:
    description: 'The ed25519 fingerprint for your tmate server'
    required: false
    default: ''
  github-token:
    description: >
      Personal access token (PAT) used to call into GitHub's REST API.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}