name: Manual test matrix
on: workflow_dispatch

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - macos-11.0
          - windows-2019
        limit-access-to-actor:
          - true
          - false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          limit-access-to-actor: ${{ matrix.limit-access-to-actor }}
