name: Manual test matrix
on: workflow_dispatch

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-11.0
          - macos-12.0
          - windows-2019
          - windows-2022
        limit-access-to-actor:
          - true
          - false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          limit-access-to-actor: ${{ matrix.limit-access-to-actor }}
  test-container:
    strategy:
      fail-fast: false
      matrix:
        container-runs-on:
          - fedora:latest
          - archlinux:latest
          - ubuntu:latest
        limit-access-to-actor:
          - true
          - false
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container-runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          limit-access-to-actor: ${{ matrix.limit-access-to-actor }}
